fixing tests and fixtures

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -20,8 +20,20 @@ jobs:
         with:
           python-version: '3.12'
 
+      - name: Install system dependencies
+        run: sudo apt-get install -y libkrb5-dev krb5-user
+
+      - name: Check krb5-config availability
+        run: which krb5-config || echo "krb5-config not found"
+
       - name: Install Poetry
         run: pipx install poetry
+
+      - name: Clear Poetry Cache
+        run: poetry cache clear --all pypi
+
+      - name: Install gssapi manually (test)
+        run: pip install gssapi
 
       - name: Install dependencies
         run: poetry install
