messing with pipeline2

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -21,7 +21,10 @@ jobs:
           python-version: '3.12'
 
       - name: Install system dependencies
-        run: sudo apt-get install -y libkrb5-dev
+        run: sudo apt-get install -y libkrb5-dev krb5-user
+
+      - name: Check krb5-config availability
+        run: which krb5-config || echo "krb5-config not found"
 
       - name: Install Poetry
         run: pipx install poetry
@@ -29,8 +32,8 @@ jobs:
       - name: Clear Poetry Cache
         run: poetry cache clear --all pypi
 
-      - name: Install gssapi with Poetry
-        run: poetry add gssapi@1.9.0
+      - name: Install gssapi manually (test)
+        run: pip install gssapi
 
       - name: Install dependencies
         run: poetry install
